api:
  enabled: false
  port: 13091
app:
  beta: false
  autoupdate: true
  autostart: true
  autostartMinimized: true
  getstarted: true
  enableDev: false
  minimizeTrayOverride: false
  enableStatisticsAndErrorTracing: true
  disableHardwareAccel: false
  enableTaskbarProgress: true
volumeRatio:
  enabled: true
  volume: 0.1
player:
  skipDisliked: false
  res:
    enabled: false
    prefer: auto
discord:
  enabled: false
  buttons: false
customcss:
  enabled: true
  scssFile: /home/zenitsu/Documents/ytmdesktop/custom.scss
  watching: false
  thumbnailBackground: true
state:
  currentUrl: null
lastfm:
  enabled: false
__internal__:
  migrationVersion: 4
plugins:
  bypass_age_restrictions:
    enabled: true
